apiVersion: v1
kind: Service
metadata:
  name: {{ include "youtube-downloader.fullname" . }}
  labels:
    {{- include "youtube-downloader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "youtube-downloader.selectorLabels" . | nindent 4 }}
